spring.application.name=ai-learning
spring.profiles.active=local
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.options.model=gpt-4o-mini
spring.ai.openai.chat.options.max-tokens=500

#pgvector config
spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.vectorstore.pgvector.dimensions=1536
spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE

# Circuit Breaker config
resilience4j.circuitbreaker.instances.llmService.sliding-window-size=5
resilience4j.circuitbreaker.instances.llmService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.llmService.wait-duration-in-open-state=30s
resilience4j.circuitbreaker.instances.llmService.permitted-calls-in-half-open-state=2
resilience4j.circuitbreaker.instances.llmService.automatic-transition-from-open-to-half-open-enabled=true

# Retry config
resilience4j.retry.instances.llmService.max-attempts=3
resilience4j.retry.instances.llmService.wait-duration=2s
resilience4j.retry.instances.llmService.enable-exponential-backoff=true
resilience4j.retry.instances.llmService.exponential-backoff-multiplier=2
